# Generated by Django 4.2.1 on 2023-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=220)),
                ('age', models.CharField(max_length=220)),
                ('gender', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('classs', models.CharField(max_length=220)),
            ],
        ),
    ]
